<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRxaMx4d\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRxaMx4d/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRxaMx4d.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRxaMx4d\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRxaMx4d\App_KernelDevDebugContainer([
    'container.build_hash' => 'RxaMx4d',
    'container.build_id' => '7a9e9aef',
    'container.build_time' => 1748264093,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRxaMx4d');
